sudo: required
services:
  - docker

before_install:
  - docker build -t daytalker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true daytalker/react-test npm test

after_success:
  - docker build -t daytalker/multi-client ./client
  - docker build -t daytalker/multi-server ./server
  - docker build -t daytalker/multi-worker ./worker
  - docker build -t daytalker/multi-nginx ./nginx